name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Debug dist folder structure
        run: |
          echo "Contents of dist folder:"
          ls -R ./dist
          echo ""
          echo "Checking index.html links:"
          if [ -f "./dist/index.html" ]; then
            grep -E 'src="|href="' ./dist/index.html
          fi

      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Verify deployment files
        run: |
          echo "Files to be deployed:"
          ls -R ./dist
          echo ""
          echo "Checking file sizes:"
          du -sh ./dist/*

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
